[package]
name = "convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
graphalgs = "0.1.1"
image = "0.24.7"
petgraph = "0.6.4"
walky = "1.1.0"
